# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_json', models.TextField()),
                ('output_json', models.TextField()),
                ('function_name', models.CharField(max_length=100)),
                ('success', models.BooleanField()),
            ],
        ),
    ]
