# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_testing', '0002_requestentry_test_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestentry',
            name='previous_method',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
