# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_testing', '0003_requestentry_previous_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestentry',
            name='previous_method',
        ),
        migrations.AddField(
            model_name='requestentry',
            name='previous_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ajax_testing.RequestEntry'),
        ),
    ]
