# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_testing', '0004_auto_20170124_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestentry',
            name='input_json',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='requestentry',
            name='output_json',
            field=models.BinaryField(),
        ),
    ]
