# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_testing', '0005_auto_20170411_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestentry',
            name='previous_request',
        ),
    ]
